package com.sidephone.demogame.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightColorScheme = lightColorScheme(
	primary = Color(0xFF000000),
	onPrimary = Color(0xFFFFFFFF),
//	secondary = ...
//	onSecondary = ...
//	tertiary = ...
//	onTertiary = ...
//	background = ...
//	onBackground = ...
//	surface = ...
//	onSurface = ...
//	onSurfaceVariant = ...
)

val DarkColorScheme = darkColorScheme(
	primary = Color(0xFFFFFFFF),
	onPrimary = Color(0xFF000000),
//	secondary = ...
//	onSecondary = ...
//	tertiary = ...
//	onTertiary = ...
//	background = ...
//	onBackground = ...
//	surface = ...
//	onSurface = ...
//	onSurfaceVariant = ...
)
